ARG BASE_IMG
FROM $BASE_IMG
# opendatacube/datacube-core:1.7
# jcrattzama/cube-in-a-box:odc1.8.3

# Install setuptools to install from binary.
# RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
#         python3-setuptools && \
#     rm -rf /var/lib/apt/lists/*

USER root

WORKDIR /build

COPY docker/entrypoint.sh docker/entrypoint.sh
RUN chmod 744 docker/entrypoint.sh

COPY requirements_core.txt requirements_core.txt
RUN pip3 install -r requirements_core.txt

ARG REQS_PATH
COPY $REQS_PATH $REQS_PATH
RUN pip3 install -r $REQS_PATH

# Setup the Open Data Cube configuration.
ARG ODC_DB_HOSTNAME="odc-db"
ARG ODC_DB_DATABASE="datacube"
ARG ODC_DB_USER="dc_user"
ARG ODC_DB_PASSWORD="localuser1234"
ARG ODC_DB_PORT="5432"
ENV ODC_DB_HOSTNAME=${ODC_DB_HOSTNAME} \
    ODC_DB_DATABASE=${ODC_DB_DATABASE} \
    ODC_DB_USER=${ODC_DB_USER} \
    ODC_DB_PASSWORD=${ODC_DB_PASSWORD} \
    ODC_DB_PORT=${ODC_DB_PORT}
RUN mkdir -p /config && echo "\
[datacube] \n\
db_hostname: ${ODC_DB_HOSTNAME} \n\
db_database: ${ODC_DB_DATABASE} \n\
db_username: ${ODC_DB_USER} \n\
db_password: ${ODC_DB_PASSWORD} \n" > /config/datacube.conf
RUN cp /config/datacube.conf /etc/datacube.conf
ENV DATACUBE_CONFIG_PATH=/config/datacube.conf

ARG WORKDIR=/indexer
WORKDIR $WORKDIR

COPY Data/ Data/
COPY datasets/ .
COPY utils/ utils/
COPY index_scripts/ index_scripts/
# /home/amalocaluser/Datacube/Datacube-J/data_cube_notebooks/notebooks/Drone/Data/ Data/

ENTRYPOINT ["/build/docker/entrypoint.sh"]
CMD ["tail -f /dev/null"]
